-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Admins)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text not null,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. PRODUCTS
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text not null unique,
  price numeric not null,
  old_price numeric,
  stock integer default 0,
  status text default 'in_stock' check (status in ('in_stock', 'out_of_stock')),
  short_description text,
  description text,
  gender text,
  style text,
  main_image text,
  images text[], -- Array of image URLs
  sizes text[], -- Array of sizes (e.g., ['40', '41'])
  badge text,
  delivery_delay text default '24h–72h',
  delivery_zone text default 'Ouaga & Provinces',
  rating numeric default 5.0,
  reviews_count integer default 0
);

alter table public.products enable row level security;

create policy "Products are viewable by everyone."
  on products for select
  using ( true );

create policy "Admins can insert products."
  on products for insert
  with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Admins can update products."
  on products for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Admins can delete products."
  on products for delete
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- 3. ORDERS
create table public.orders (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text, -- Optional if not logged in
  phone text not null,
  city text, -- 'Ouagadougou' or 'Autre'
  address text,
  delivery_mode text check (delivery_mode in ('livraison', 'retrait')),
  total_amount numeric not null,
  status text default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  payment_method text default 'cash' -- 'cash', 'mobile_money'
);

alter table public.orders enable row level security;

create policy "Admins can view all orders."
  on orders for select
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Anyone can create an order."
  on orders for insert
  with check ( true );

-- 4. ORDER ITEMS
create table public.order_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id uuid references public.orders(id) on delete cascade not null,
  product_id bigint references public.products(id) not null,
  quantity integer default 1,
  size text,
  price_at_purchase numeric not null -- Store price at time of purchase
);

alter table public.order_items enable row level security;

create policy "Admins can view all order items."
  on order_items for select
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Anyone can create order items."
  on order_items for insert
  with check ( true );

-- 5. STORAGE BUCKETS (for images)
-- Note: You need to create a bucket named 'products' in Supabase Storage manually or via API.
-- This SQL sets up the policies for it.

-- Policy to allow public access to product images
-- (This usually needs to be done in the Storage section of Supabase dashboard, but here is the logic)
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'products' );

-- Policy to allow admins to upload images
-- create policy "Admin Upload" on storage.objects for insert with check ( bucket_id = 'products' and exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- TRIGGER: Handle new user signup to create profile
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- SEED DATA (Optional)
insert into public.products (name, slug, price, old_price, stock, short_description, description, gender, style, main_image, images, sizes, badge)
values 
('Street Runner 2025', 'street-runner-2025', 7000, 10000, 15, 'L''alliance parfaite entre confort et style urbain.', 'Description complète...', 'Unisexe', 'Street', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff', ARRAY['https://images.unsplash.com/photo-1542291026-7eec264c27ff'], ARRAY['40', '41', '42', '43', '44'], 'Nouveau');
